stages: 
  preprocess:
    cmd: python src/data/preprocess.py
    deps:
      - src/data/preprocess.py
      - data/raw/appliances_reviews_sample_200k.csv
      - params.yaml
    outs:
      - data/processed/train.csv
      - data/processed/val.csv
      - data/processed/test.csv
    
