"""init serving schema

Revision ID: 3673af78c6a5
Revises: 
Create Date: 2026-06-23 21:58:30.606606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3673af78c6a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insight_jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_insight_jobs_product_id'), 'insight_jobs', ['product_id'], unique=False)
    op.create_table('product_insights',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('product_id', 'model_version')
    )
    op.create_table('products',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('product_title', sa.Text(), nullable=True),
    sa.Column('store', sa.String(), nullable=True),
    sa.Column('main_category', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('rating_number', sa.Integer(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('avg_review_rating', sa.Float(), nullable=True),
    sa.Column('verified_review_count', sa.Integer(), nullable=True),
    sa.Column('total_helpful_votes', sa.Integer(), nullable=True),
    sa.Column('latest_review_ts', sa.BigInteger(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('categories_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('features_text', sa.Text(), nullable=True),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('review_title', sa.Text(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('review_char_len', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('review_datetime', sa.String(), nullable=True),
    sa.Column('helpful_vote', sa.Integer(), nullable=True),
    sa.Column('verified_purchase', sa.Boolean(), nullable=True),
    sa.Column('has_review_image', sa.Boolean(), nullable=True),
    sa.Column('predicted_sentiment', sa.String(), nullable=True),
    sa.Column('sentiment_confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_reviews_product_id'), 'reviews', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_product_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('products')
    op.drop_table('product_insights')
    op.drop_index(op.f('ix_insight_jobs_product_id'), table_name='insight_jobs')
    op.drop_table('insight_jobs')
    # ### end Alembic commands ###
