apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ecommerce-review
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432