apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-review

resources:
  - ../../base

images:
  - name: ecommerce-review-analyzer
    newName: us-central1-docker.pkg.dev/vaulted-blend-493604-v2/ecommerce-review-analyzer/ecommerce-review-analyzer
    newTag: sentiment-final-9f8068e-20260813001956
  
  - name: ecommerce-review-dvc-puller
    newName: us-central1-docker.pkg.dev/vaulted-blend-493604-v2/ecommerce-review-analyzer/ecommerce-review-model-puller
    newTag: dvc-noscm-9f8068e-202608121946
  